
const topETFs = [
    "VOO", "SPY", "IVV", "VTI", "QQQ", "VEA", "VUG", "IEFA", "VTV", "BND",
    "AGG", "GLD", "IWF", "IJH", "VXUS", "VIG", "IEMG", "VWO", "VGT", "VO",
    "IJR", "RSP", "SCHD", "BNDX", "XLK", "ITOT", "SPLG", "EFA", "IWD", "IWM",
    "VB", "IBIT", "VYM", "VCIT", "IVW", "SCHX", "XLF", "TLT", "QUAL", "BIL",
    "IAU", "SCHF", "SGOV", "VT", "QQQM", "VEU", "VUSD", "IXUS", "JEPI", "BSV",
    "IWR", "MUB", "IWB", "VV", "SCHG", "MBB", "IVE", "DIA", "XLV", "VTEB",
    "IEF", "VCSH", "IUSB", "VNQ", "VGIT", "SPYG", "DFAC", "SCHB", "JPST",
    "DGRO", "LQD", "GOVT", "VBR", "XLE", "VONG", "SPDW", "SPYV", "SHY", "JEPQ",
    "VFH", "SCHF", "BIL", "GDX", "XLI", "XLY", "XLC", "XLP", "XLU", "XLB",
    "XLRE", "XBI", "XHB", "XME", "XOP", "XRT", "XSD", "XTL", "XAR", "XHE",
    "XHS", "XSW", "XTH", "XWEB", "XITK", "XNTK", "XSOE", "XSLV", "XSHD",
    "XSHQ", "XSMO", "XSVM", "XSVT", "XSW", "XSX", "XTL", "XTR", "XUS", "XUX",
    "XVE", "XVG", "XVT", "XVV", "XWB", "XWC", "XWD", "XWE", "XWF", "XWG",
    "XWH", "XWI", "XWJ", "XWK", "XWL", "XWM", "XWN", "XWO", "XWP", "XWQ",
    "XWR", "XWS", "XWT", "XWU", "XWV", "XWW", "XWX", "XWY", "XWZ", "XYA",
    "XYB", "XYC", "XYD", "XYE", "XYF", "XYG", "XYH", "XYI", "XYJ", "XYK",
    "XYL", "XYM", "XYN", "XYO", "XYP", "XYQ", "XYR", "XYS", "XYT", "XYU",
    "XYV", "XYW", "XYX", "XYY", "XYZ", "YAA", "YAB", "YAC", "YAD", "YAE",
    "YAF", "YAG", "YAH", "YAI", "YAJ", "YAK", "YAL", "YAM", "YAN", "YAO",
    "YAP", "YAQ", "YAR", "YAS", "YAT", "YAU", "YAV", "YAW", "YAX", "YAY",
    "YAZ", "ZAA", "ZAB", "ZAC", "ZAD", "ZAE", "ZAF", "ZAG", "ZAH", "ZAI",
    "ZAJ", "ZAK", "ZAL", "ZAM", "ZAN", "ZAO", "ZAP", "ZAQ", "ZAR", "ZAS",
    "ZAT", "ZAU", "ZAV", "ZAW", "ZAX", "ZAY", "ZAZ", "ZBA", "ZBB", "ZBC",
    "ZBD", "ZBE", "ZBF", "ZBG", "ZBH", "ZBI", "ZBJ", "ZBK", "ZBL", "ZBM",
    "ZBN", "ZBO", "ZBP", "ZBQ", "ZBR", "ZBS", "ZBT", "ZBU", "ZBV", "ZBW",
    "ZBX", "ZBY", "ZBZ", "ZCA", "ZCB", "ZCC", "ZCD", "ZCE", "ZCF", "ZCG",
    "ZCH", "ZCI", "ZCJ", "ZCK", "ZCL", "ZCM", "ZCN", "ZCO", "ZCP", "ZCQ",
    "ZCR", "ZCS", "ZCT", "ZCU", "ZCV", "ZCW", "ZCX", "ZCY", "ZCZ", "ZDA",
    "ZDB", "ZDC", "ZDD", "ZDE", "ZDF", "ZDG", "ZDH", "ZDI", "ZDJ", "ZDK",
    "ZDL", "ZDM", "ZDN", "ZDO", "ZDP", "ZDQ", "ZDR", "ZDS", "ZDT", "ZDU",
    "ZDV", "ZDW", "ZDX", "ZDY", "ZDZ", "ZEA", "ZEB", "ZEC", "ZED", "ZEE",
    "ZEF", "ZEG", "ZEH", "ZEI", "ZEJ", "ZEK", "ZEL", "ZEM", "ZEN", "ZEO",
    "ZEP", "ZEQ", "ZER", "ZES", "ZET", "ZEU", "ZEV", "ZEW", "ZEX", "ZEY",
    "ZEZ", "ZFA", "ZFB", "ZFC", "ZFD", "ZFE", "ZFF", "ZFG", "ZFH", "ZFI",
    "ZFJ", "ZFK", "ZFL", "ZFM", "ZFN", "ZFO", "ZFP", "ZFQ", "ZFR", "ZFS",
    "ZFT", "ZFU", "ZFV", "ZFW", "ZFX", "ZFY", "ZFZ", "ZGA", "ZGB", "ZGC",
    "ZGD", "ZGE", "ZGF", "ZGG", "ZGH", "ZGI", "ZGJ", "ZGK", "ZGL", "ZGM",
    "ZGN", "ZGO", "ZGP", "ZGQ", "ZGR", "ZGS", "ZGT", "ZGU", "ZGV", "ZGW",
    "ZGX", "ZGY", "ZGZ", "ZHA", "ZHB", "ZHC", "ZHD", "ZHE", "ZHF", "ZHG",
    "ZHH", "ZHI", "ZHJ", "ZHK", "ZHL", "ZHM", "ZHN", "ZHO", "ZHP", "ZHQ",
    "ZHR", "ZHS", "ZHT", "ZHU", "ZHV", "ZHW", "ZHX", "ZHY", "ZHZ", "ZIA",
    "ZIB", "ZIC", "ZID", "ZIE", "ZIF", "ZIG", "ZIH", "ZII", "ZIJ", "ZIK",
    "ZIL", "ZIM", "ZIN", "ZIO", "ZIP", "ZIQ", "ZIR", "ZIS", "ZIT", "ZIU",
    "ZIV", "ZIW", "ZIX", "ZIY", "ZIZ", "ZJA", "ZJB", "ZJC", "ZJD", "ZJE",
    "ZJF", "ZJG", "ZJH", "ZJI", "ZJJ", "ZJK", "ZJL", "ZJM", "ZJN", "ZJO",
    "ZJP", "ZJQ", "ZJR", "ZJS", "ZJT", "ZJU", "ZJV", "ZJW", "ZJX", "ZJY",
    "ZJZ", "ZKA", "ZKB", "ZKC", "ZKD", "ZKE", "ZKF", "ZKG", "ZKH", "ZKI",
    "ZKJ", "ZKK", "ZKL", "ZKM", "ZKN", "ZKO", "ZKP", "ZKQ", "ZKR", "ZKS",
    "ZKT", "ZKU", "ZKV", "ZKW", "ZKX", "ZKY", "ZKZ", "ZLA", "ZLB", "ZLC",
    "ZLD", "ZLE", "ZLF", "ZLG", "ZLH", "ZLI", "ZLJ", "ZLK", "ZLL", "ZLM",
    "ZLN", "ZLO", "ZLP", "ZLQ", "ZLR", "ZLS", "ZLT", "ZLU", "ZLV", "ZLW",
    "ZLX", "ZLY", "ZLZ", "ZMA", "ZMB", "ZMC", "ZMD", "ZME", "ZMF", "ZMG",
    "ZMH", "ZMI", "ZMJ", "ZMK", "ZML", "ZMM", "ZMN", "ZMO", "ZMP", "ZMQ",
    "ZMR", "ZMS", "ZMT", "ZMU", "ZMV", "ZMW", "ZMX", "ZMY", "ZMZ", "ZNA",
    "ZNB", "ZNC", "ZND", "ZNE", "ZNF", "ZNG", "ZNH", "ZNI", "ZNJ", "ZNK"
];



const KNOWN_INDEXES = [
  { name: 'S&P 500', keywords: ['S&P 500', "Standard & Poor's 500"] },
  { name: 'S&P Mid-Cap 400', keywords: ['S&P 400', 'Mid-Cap 400', 'S&P MidCap', 'S&P Mid-Cap'] },
  { name: 'S&P SmallCap 600', keywords: ['S&P 600', 'SmallCap 600'] },
  { name: 'S&P Biotech', keywords: ['S&P Biotech', 'S&P Biotechnology', 'S&P Biotech Index'] },
  { name: 'S&P Bank', keywords: ['S&P Bank', 'S&P Bank Index'] },
  { name: 'S&P Capital Markets', keywords: ['Capital Markets', 'S&P Capital Markets'] },
  { name: 'NASDAQ-100', keywords: ['NASDAQ-100', 'Nasdaq 100', 'NDX'] },
  { name: 'NASDAQ Composite', keywords: ['NASDAQ Composite', 'Nasdaq Composite'] },
  { name: 'Russell 1000', keywords: ['Russell 1000'] },
  { name: 'Russell 2000', keywords: ['Russell 2000'] },
  { name: 'Russell 3000', keywords: ['Russell 3000'] },
  { name: 'Russell Top 200', keywords: ['Russell Top 200'] },
  { name: 'CRSP US Total Market', keywords: ['CRSP US', 'CRSP US Total', 'CRSP US Total Market', 'CRSP'] },
  { name: 'FTSE Developed', keywords: ['FTSE Developed', 'FTSE Developed Index'] },
  { name: 'FTSE All-World', keywords: ['FTSE All-World', 'FTSE World', 'FTSE All World'] },
  { name: 'Wilshire 5000', keywords: ['Wilshire 5000'] },
  { name: 'Total Stock Market', keywords: ['Total Stock Market'] },
  { name: 'Total Bond Market', keywords: ['Total Bond', 'Aggregate Bond', 'AGG', 'Total Bond Market'] },
  { name: 'Long-Term Bond', keywords: ['Long-Term Bond', 'Long Duration', 'Long-Term Treasury'] },
  { name: 'Short-Term Treasury', keywords: ['Short-Term Treasury', 'Short-Term U.S. Treasury', 'Short Duration Treasury', 'Short-Term Bond'] },
  { name: 'Floating Rate Treasury', keywords: ['Floating Rate Treasury', 'USFR', 'Floating Rate Note'] },
  { name: 'Municipal Bond', keywords: ['Municipal Bond', 'Muni Bond', 'Municipals'] },
  { name: 'ChiNext', keywords: ['ChiNext'] },
  { name: 'Bitcoin', keywords: ['Bitcoin', 'BTC'] },
  { name: 'StrategicFactors', keywords: ['StrategicFactors', 'MSCI USA StrategicFactors', 'USA StrategicFactors'] },
  { name: 'SMid Cap', keywords: ['SMid Cap', 'Small-Mid Cap', 'Small & Mid Cap', 'SMid Growth'] },
  { name: 'Buffer Strategy', keywords: ['Buffer ETF', 'Moderate Buffer', 'Laddered Buffer', 'Buffer Strategy'] },
  { name: 'Dow Jones Industrial Average', keywords: ['Dow Jones', 'DJIA', 'Dow 30', 'Dow'] },
{ name: 'NYSE Composite', keywords: ['NYSE Composite', 'NYSE Index'] },
{ name: 'S&P 100', keywords: ['S&P 100', 'OEX'] },
{ name: 'S&P 1500', keywords: ['S&P 1500', 'S&P Composite 1500'] },
{ name: 'S&P 900', keywords: ['S&P 900'] },
{ name: 'CRSP US Mega Cap', keywords: ['CRSP US Mega Cap'] },
{ name: 'CRSP US Mid Cap', keywords: ['CRSP US Mid Cap'] },
{ name: 'CRSP US Small Cap', keywords: ['CRSP US Small Cap'] },
{ name: 'CRSP US Large Cap', keywords: ['CRSP US Large Cap'] },
{ name: 'Barclays U.S. Aggregate Bond', keywords: ['Barclays Aggregate Bond', 'Barclays U.S. Aggregate', 'Bloomberg Barclays Aggregate'] },

];







const topDerivatives = [

  { name: 'S&P 500 Futures (proxy: SPDR S&P 500 ETF)', ticker: 'SPY' },
  { name: 'Nasdaq-100 Futures (proxy: Invesco QQQ Trust)', ticker: 'QQQ' },
  { name: 'Dow Jones Futures (proxy: SPDR Dow Jones ETF)', ticker: 'DIA' },
  { name: 'Russell 2000 Futures (proxy: iShares Russell 2000 ETF)', ticker: 'IWM' },
  { name: 'DAX Futures (proxy: Global X DAX Germany ETF)', ticker: 'DAX' },
  { name: 'EURO STOXX 50 Futures (proxy: FEZ - SPDR EURO STOXX 50)', ticker: 'FEZ' },
  { name: 'FTSE 100 Futures (proxy: iShares MSCI UK ETF)', ticker: 'EWU' },
  { name: 'Nikkei 225 Futures (proxy: iShares MSCI Japan ETF)', ticker: 'EWJ' },
  { name: 'Hang Seng Futures (proxy: iShares Hong Kong ETF)', ticker: 'EWH' },
  { name: 'China A50 Futures (proxy: iShares China Large-Cap ETF)', ticker: 'FXI' },
  { name: 'Gold Futures (proxy: SPDR Gold Shares)', ticker: 'GLD' },
  { name: 'Silver Futures (proxy: iShares Silver Trust)', ticker: 'SLV' },
  { name: 'Crude Oil Futures (proxy: United States Oil Fund)', ticker: 'USO' },
  { name: 'Natural Gas Futures (proxy: United States Natural Gas Fund)', ticker: 'UNG' },
  { name: 'VIX Futures (proxy: ProShares VIX Short-Term Futures)', ticker: 'VIXY' },
  { name: 'Treasury Futures (proxy: iShares 20+ Year Treasury Bond ETF)', ticker: 'TLT' },
  { name: 'Eurodollar Futures (no ETF proxy available)', ticker: null }, // purely institutional
];

